const boxen = require("boxen");
const chalk = require("chalk");
const grad = require('gradient-string');
const figlet = require('figlet');



exports.sentences =
    [
        "Amis de la ligne de commande, bienvenue dans cette aventure interactive. Vous allez vivre une expérience qui va vous rappeller votre enfance. Pour participer, lisez le premier paragraphe, vous devrez faire un choix. Entrez le numéro correspondant à votre choix et appuyez sur [ENTER]. Pour commencer, entrez le chiffre 1",
        "Tu as toujours rêvé de faire le " + grad.morning("tour du monde") + ", donc depuis un moment, tu économises et te prépare. Nous sommes le jour avant ton départ et tu te retrouves face à un choix: \n\n* Checker un dernier coup ta valise (20) \n* Profiter une dernière fois de ta baignoire (31) ",
        "My Second Sentence",
        "This is the third",
        "And the fourth",
        "Fifth is here too",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Tu te rends dans ta chambre et la...",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Tu entres dans la salle de bain, et ouvre le robinet de la baignoire en grand. L'eau s'accumule doucement et tu te dis qu'un peu de musique serait agréable.",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        
    ]
