const boxen = require("boxen");
const chalk = require("chalk");
const grad = require('gradient-string');
const figlet = require('figlet');
const strbr = require('string-break');


exports.sentences =
    [
        "Amis de la ligne de commande, bienvenue dans cette aventure interactive. Vous allez vivre une expérience qui va vous rappeller votre enfance. Pour participer, lisez le premier paragraphe, vous devrez faire un choix. Entrez le numéro correspondant à votre choix et appuyez sur [ENTER]. Pour commencer, entrez le chiffre 1",
        "Tu as toujours rêvé de faire le tour du monde, donc depuis un moment, tu économises et te prépare. Nous sommes le jour avant ton départ et tu te retrouves face à un choix: \n\n-Checker un dernier coup ta valise (20) \n-Profiter une dernière fois de ta baignoire (31) ",
        chalk.red("Qu'est-ce que tu fais la ? Sans déconner! Retourne en 1!"),
        chalk.red("Bon... visiblement y'a rien a faire pour toi, Ouste! Retourne en 1"),
        "And the fourth",
        "Fifth is here too",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Tu te rends dans le séjour, et tu te souviens que la chaine Hifi n'est plus branchée... un problème de prise électrique... tu as donc deux choix: \n-Faire demi-tour et utiliser finalement ton portable (34). \n-Aller chercher la rallonge dans la remise et tout brancher(44).",
        "Qu'est ce que tu fais la ? Retourne en (1)",
        "Tu déplies la pochette contenant tout tes documents de voyage et les passes en revue. Carte d'identité, passeport, Billets d'avion.. 1,2,3... IL EN MANQUE UN ! Et comble de malchance, c'est le premier vol que tu dois prendre, avant de faire correspondance pour la suite, tu ne peux te permettre de le rater... \n-Chercher du coté de ton bureau(60). \n-Chercher dans la chambre(51). ",
        "",
        "",
        "",
        "",
        "Tu te rends dans la chambre, la valise trône fièrement sur le lit. Que viens-tu vérifier ? \n-Les documents de voyage(15). \n-Le contenu de la trousse d'urgence(26).",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Tu entres dans la salle de bain, et ouvre le robinet de la baignoire en grand. L'eau s'accumule doucement et tu te dis qu'un peu de musique serait quand même agréable: \n\n-Tu vas allumer la radio (13). \n-T'as la flemme, tu utilises ton portable (34).",
        "",
        "",
        "Tu poses ton portable sur le bord de la baignoire et lance la musique. Sur le rythme endiablé de 'Jail House Rock' tu te déchaînes..Mais qui peut te stopper ?!? Bah le mur. Complètement possédé, tu as tenté un mouvement inexplicable qui t'as amené a te cogner sévèrement sur le mur. T'es tombé la tête la première dans la baignoire et tu t'es noyé dans ton propre bain. Le cul en l'air.\nRetour au (1).",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Tu décides d'aller chercher la rallonge et au moment ou tu sors dans ton jardin, tu tombes nez-à-truffe avec l'énorme molosse (un chihuahua croisé caniche) de ton voisin-pas-très-sympa. Celui-ci te menace d'un air mauvais, tous crocs sortis... Tu recules... Tu bascules en arrière et la... Coup du lapin sur ces saloperies de bordures que t'avais prévu d'enlever depuis que t'habites là. C'est à dire une plombe. \n\nC'est vraiment ballot, y'a plus qu'a recommencer(1).",
        "",
        "",
        "",
        "",
        "",
        "",
        "Tu commences à tout retourner, tu te retrouves à genoux sur le sol de ta chambre, pensant qu'il aurait glissé sous le lit ou un meuble. En cherchant de manière un peu trop énergique, tu donnes un coup dans l'énorme étagère sous laquelle tu regardais. Cette fameuse étagère, pleine d'énormes bouquins et de ta collection de minerais pas rares et -QUI PÈSE UNE TONNE- te bascules dessus alors que ta tête étais collée au sol.\n\n On ne connait pas trop les détails de ton état après ça, mais ce qui est sûr, c'est que tu ne pars pas en voyage le lendemain.",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "T'as pas rangé ton bureau et c'est bien le bordel là. Il est où ce billet ?!? Tu déplaces tout en espérant voir apparaitre ton billet... \n-Prendre le temps de ranger le bureau(8).\n-En avoir marre et aller chercher ailleurs(45).",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
    ]
